'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ForgotPassword


    '''<summary>
    '''loginForm 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents loginForm As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''ErrorMessage 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents ErrorMessage As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''FailureText 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents FailureText As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Email 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents Email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DisplayEmail 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents DisplayEmail As Global.System.Web.UI.WebControls.PlaceHolder
End Class
