'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManagePassword

    '''<summary>
    '''setPassword 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents setPassword As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''password 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''confirmPassword 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents confirmPassword As Global.System.Web.UI.WebControls.TextBox    

    '''<summary>
    '''changePasswordHolder 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents changePasswordHolder As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''CurrentPasswordLabel 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents CurrentPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CurrentPassword 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents CurrentPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NewPasswordLabel 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents NewPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NewPassword 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents NewPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ConfirmNewPasswordLabel 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents ConfirmNewPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ConfirmNewPassword 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents ConfirmNewPassword As Global.System.Web.UI.WebControls.TextBox
End Class
