'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TwoFactorAuthenticationSignIn

    '''<summary>
    '''sendcode 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents sendcode As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Providers 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents Providers As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ProviderSubmit 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents ProviderSubmit As Global.System.Web.UI.WebControls.Button    

    '''<summary>
    '''verifycode 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents verifycode As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''SelectedProvider 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents SelectedProvider As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ErrorMessage 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents ErrorMessage As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''FailureText 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents FailureText As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Code 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents Code As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RememberBrowser 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents RememberBrowser As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CodeSubmit 컨트롤입니다.
    '''</summary>
    '''<remarks>
    '''자동 생성된 필드입니다.
    '''수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
    '''</remarks>
    Protected WithEvents CodeSubmit As Global.System.Web.UI.WebControls.Button
End Class
